# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x13grpc_implementation\x1a\x1bgoogle/protobuf/empty.proto\"D\n\nServerList\x12\x36\n\nserverList\x18\x01 \x03(\x0b\x32\".grpc_implementation.ServerMessage\"@\n\x0b\x41rticleList\x12\x31\n\x0b\x61rticleList\x18\x01 \x03(\x0b\x32\x1c.grpc_implementation.Article\"l\n\x0e\x41rticleRequest\x12+\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x1b.grpc_implementation.Client\x12-\n\x07\x61rticle\x18\x02 \x01(\x0b\x32\x1c.grpc_implementation.Article\"\x14\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\".\n\rServerMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"Q\n\x07\x41rticle\x12\x0f\n\x05_type\x18\x01 \x01(\tH\x00\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\tB\x06\n\x04type\"5\n\x06Result\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.grpc_implementation.Status*\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\xad\x01\n\x0eServerRegistry\x12Q\n\x0eRegisterServer\x12\".grpc_implementation.ServerMessage\x1a\x1b.grpc_implementation.Result\x12H\n\rGetServerList\x12\x16.google.protobuf.Empty\x1a\x1f.grpc_implementation.ServerList2\xc1\x02\n\x06Server\x12\x46\n\nJoinServer\x12\x1b.grpc_implementation.Client\x1a\x1b.grpc_implementation.Result\x12\x46\n\nLeaveSever\x12\x1b.grpc_implementation.Client\x1a\x1b.grpc_implementation.Result\x12R\n\x0ePublishArticle\x12#.grpc_implementation.ArticleRequest\x1a\x1b.grpc_implementation.Result\x12S\n\nGetArticle\x12#.grpc_implementation.ArticleRequest\x1a .grpc_implementation.ArticleListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=522
  _STATUS._serialized_end=553
  _SERVERLIST._serialized_start=68
  _SERVERLIST._serialized_end=136
  _ARTICLELIST._serialized_start=138
  _ARTICLELIST._serialized_end=202
  _ARTICLEREQUEST._serialized_start=204
  _ARTICLEREQUEST._serialized_end=312
  _CLIENT._serialized_start=314
  _CLIENT._serialized_end=334
  _SERVERMESSAGE._serialized_start=336
  _SERVERMESSAGE._serialized_end=382
  _ARTICLE._serialized_start=384
  _ARTICLE._serialized_end=465
  _RESULT._serialized_start=467
  _RESULT._serialized_end=520
  _SERVERREGISTRY._serialized_start=556
  _SERVERREGISTRY._serialized_end=729
  _SERVER._serialized_start=732
  _SERVER._serialized_end=1053
# @@protoc_insertion_point(module_scope)
